/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


/******************************************************************************/
/*                              INCLUDE FILES                                 */
/******************************************************************************/
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>


#include "system_stm32f4xx.h"
#include "timer.h"
#include "eventman.h"
#include "led.h"
#include "melody.h"
#include "lightsensor.h"
#include "temhumsensor.h"
#include "eventbutton.h"
#include "button.h"
#include "Ucglib.h"


/******************************************************************************/
/*                     PRIVATE TYPES and DEFINITIONS                         */
/******************************************************************************/
typedef enum{
	EVENT_EMPTY,
	EVENT_APP_INIT,
	EVENT_APP_FLUSHMEM_READY
}	event_api_t, *event_api_p;

typedef enum{
	STATE_APP_STARTUP,
	STATE_APP_IDLE,
	STATE_APP_RESET
} state_app_t;
/******************************************************************************/
/*                     EXPORTED TYPES and DEFINITIONS                         */
/******************************************************************************/


/******************************************************************************/
/*                              PRIVATE DATA                                  */
/******************************************************************************/
static ucg_t ucg;
static state_app_t eCurrentState;
static uint8_t IdTimer = NO_TIMER;
static uint8_t levelLed = 0;
static uint8_t IdTimerCancle;
/******************************************************************************/
/*                              EXPORTED DATA                                 */
/******************************************************************************/

/******************************************************************************/
/*                            PRIVATE FUNCTIONS                               */
/******************************************************************************/
static void AppStateManager(uint8_t);
static void SetStateApp(state_app_t);
static state_app_t GetStateApp(void);
void DeviceStateMachine(uint8_t event);
void LoadConfiguration(void);
void AppInitCommon(void);

void LedUp(void *data);
void LedDown(void *data);

void cancleTimer(void *data);

/******************************************************************************/
/*                            EXPORTED FUNCTIONS                              */
/******************************************************************************/

/******************************************************************************/
void AppInitCommon()
{
	SystemCoreClockUpdate();
	TimerInit();
	EventButton_Init();
	BuzzerControl_Init();
	LedControl_Init();
	LightSensor_Init(ADC_READ_MODE_DMA);
	TemHumSensor_Init();

	EventSchedulerInit(AppStateManager);

}

static void AppStateManager(uint8_t event)
{
	switch(GetStateApp())
	{
	case STATE_APP_STARTUP:
		if(event == EVENT_APP_INIT)
		{
			//Load configuration
			LoadConfiguration();
			SetStateApp(STATE_APP_IDLE);

		}
		break;

	case STATE_APP_IDLE:
		DeviceStateMachine(event);
		break;

	case STATE_APP_RESET:
		break;

	default:
		break;
	}
}

static void SetStateApp(state_app_t state)
{
	eCurrentState = state;
}

static state_app_t GetStateApp(void)
{
	return eCurrentState;
}
/*hàm cho câu 1: hiển thị dòng chữ lên LCD*/
void LoadConfiguration(void){

	//hỏi anh trung tại sao config LCD trên appInitCommon ko đc

	/*************		setup LCD		****************/
	Ucglib4WireSWSPI_begin(&ucg, UCG_FONT_MODE_SOLID);
	ucg_ClearScreen(&ucg);

	ucg_SetFont(&ucg, ucg_font_helvR08_tf);
	ucg_SetColor(&ucg, 0, 255, 255, 255);
	ucg_SetColor(&ucg, 1, 0, 0, 0);
	ucg_SetRotate180(&ucg);
	ucg_DrawString(&ucg, 5, 12, 0, "IOT Programming");
	ucg_DrawString(&ucg, 5, 26, 0, "by Lumi Smarthome");
}


static uint8_t count = 0;
static uint8_t brightness = 0;
void blinkLed(void *data) { //hàm nháy led sau 5 lần nhấn B3 trên board
    if (count < 10) { //cứ 2 giá trị của count là 1 lần bật&tắt
        if (brightness == 0) {
            brightness = 50;
        } else {
            brightness = 0;
        }

        // Bật/tắt LED với độ sáng mới
        LedControl_SetAllColor(LED_COLOR_GREEN, brightness);
        count++;
    }
}


void DeviceStateMachine(uint8_t event)
{
	switch(event)
	{
	/*hàm cho câu 2: Nhấn nút B3 năm lần khi đó tất cả các Led trên Kit
	mở rộng sẽ nháy năm lần màu GREEN với cường độ sáng là 50% và hiển
	thị thông tin sau thiết bị lên màn hình LCD*/
		case EVENT_OF_BUTTON_0_PRESS_5_TIMES:
		{
			if(IdTimer != NO_TIMER)
			{
				TimerStop(IdTimer);
				IdTimer = NO_TIMER;
			}
			count = 0;
			IdTimer = TimerStart("BlinkTimer", 500, 10,(void*) blinkLed, NULL);

			ucg_ClearScreen(&ucg);
			ucg_DrawString(&ucg, 0, 12, 0, "DEVICE: Board STM32");
			ucg_DrawString(&ucg, 0, 24, 0, "Nucleo");
			ucg_DrawString(&ucg, 0, 36, 0, "CODE: ");
			ucg_DrawString(&ucg, 0, 48, 0, "STM32F401RE_NUCLEO");
			ucg_DrawString(&ucg, 0, 60, 0, "MANUFACTURER: ");
			ucg_DrawString(&ucg, 0, 72, 0, "STMicroelectronics");
			ucg_DrawString(&ucg, 0, 84, 0, "KIT EXPANSION: ");
			ucg_DrawString(&ucg, 0, 96, 0, "Lumi Smarthome");
			ucg_DrawString(&ucg, 0, 108, 0, "PROJECT: ");
			ucg_DrawString(&ucg, 0, 120, 0, "Simulator touch switch");

		}	break;


		static uint8_t button1count = 0;
		case EVENT_OF_BUTTON_1_PRESS_LOGIC:
		{
			if(button1count == 0)
			{
				LedControl_SetAllColor(LED_COLOR_RED, 50);
				BuzzerControl_SetMelody(pbeep);
				button1count = 1;
			}else{
				LedControl_SetAllColor(LED_COLOR_RED, 0);
				BuzzerControl_SetMelody(pbeep);
				button1count = 0;
			}

		}	break;


		static uint8_t button2count = 0;
		case EVENT_OF_BUTTON_2_PRESS_LOGIC:
		{
			if(button2count == 0)
			{
				LedControl_SetAllColor(LED_COLOR_GREEN, 50);
				BuzzerControl_SetMelody(pbeep);
				button2count = 1;
			}else{
				LedControl_SetAllColor(LED_COLOR_GREEN, 0);
				BuzzerControl_SetMelody(pbeep);
				button2count = 0;
			}
		}	break;

		static uint8_t button4count = 0;
		case EVENT_OF_BUTTON_4_PRESS_LOGIC:
		{
			if(button4count == 0)
			{
				LedControl_SetAllColor(LED_COLOR_WHITE, 50);
				BuzzerControl_SetMelody(pbeep);
				button4count = 1;
			}else{
				LedControl_SetAllColor(LED_COLOR_WHITE, 0);
				BuzzerControl_SetMelody(pbeep);
				button4count = 0;
			}
		}	break;


		static uint8_t button5count = 0;
		case EVENT_OF_BUTTON_5_PRESS_LOGIC:
		{
			if(button5count == 0)
			{
				LedControl_SetAllColor(LED_COLOR_BLUE, 50);
				BuzzerControl_SetMelody(pbeep);
				button5count = 1;
			}else{
				LedControl_SetAllColor(LED_COLOR_BLUE, 0);
				BuzzerControl_SetMelody(pbeep);
				button5count = 0;
			}
		}	break;




		case EVENT_OF_BUTTON_1_HOLD_1S:
		{
			if(IdTimer != NO_TIMER)
			{
				TimerStop(IdTimer);
				IdTimer = NO_TIMER;
			}

			IdTimer = TimerStart("LedUp", 50, TIMER_REPEAT_FOREVER, (void*)LedUp, NULL);
		}	break;


		case EVENT_OF_BUTTON_5_HOLD_1S:
		{
			if(IdTimer != NO_TIMER)
			{
				TimerStop(IdTimer);
				IdTimer = NO_TIMER;
			}

			IdTimer = TimerStart("LedDown", 50, TIMER_REPEAT_FOREVER, (void*)LedDown, NULL);
		}	break;


		case EVENT_OF_BUTTON_1_RELEASED_1S:
		{
			if(IdTimer != NO_TIMER)
			{
				TimerStop(IdTimer);
				IdTimer = NO_TIMER;
			}
		} break;


		case EVENT_OF_BUTTON_5_RELEASED_1S:
		{
			if(IdTimer != NO_TIMER)
			{
				TimerStop(IdTimer);
				IdTimer = NO_TIMER;
			}
		} break;


		default:
			break;
	}
}

void LedUp(void *data)
{
	if(levelLed < 100)
	{
		LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, levelLed);
		levelLed ++;
	}
}
void LedDown(void *data)
{
	if(levelLed > 0)
	{
		LedControl_SetColorGeneral(LED_KIT_ID0, LED_COLOR_GREEN, levelLed);
		levelLed --;
	}
}
static char src1[20];
static char src2[20];
static char src3[20];
static uint8_t count_clear = 0;
void Task_multiSensorScan()
{
	uint8_t temp = TemHumSensor_GetTemp();
	uint8_t humi = TemHumSensor_GetHumi();
	uint16_t light= LightSensor_MeasureUseDMAMode();

	if(count_clear == 0){
	ucg_ClearScreen(&ucg);
	count_clear = 1;
	}

	//hiển thị nhiệt độ
	memset(src1,0,sizeof(src1));
	sprintf(src1,"Temp = %d oC", temp);
	ucg_DrawString(&ucg, 0, 12, 0, src1);


	//hiển thị độ ẩm
	memset(src2,0,sizeof(src2));
	sprintf(src2,"Humi = %3d %%", humi);
	ucg_DrawString(&ucg, 0, 48, 0, src2);


	//hiển thị ánh sáng
	memset(src3,0,sizeof(src3));
	sprintf(src3,"Light = %d lux", light);
	ucg_DrawString(&ucg, 0, 60, 0, src3);


}


static uint32_t lastUpdateTime;

static uint32_t updateInterval = 2s000;// milisecond


void cancleTimer(void *data){
	if(IdTimerCancle != NO_TIMER){
		TimerStop(IdTimerCancle);
	}
}
void MultiSensorScan()
{
//    uint32_t lastUpdateTime = GetMilSecTick();
//    uint32_t updateInterval = 1000; // 1 giây (1000 millisecond)
        uint32_t currentTime = GetMilSecTick();

        if (currentTime - lastUpdateTime >= updateInterval) {
            // Đã đủ thời gian để cập nhật nhiệt độ và độ ẩm
            // Thực hiện việc cập nhật thông tin từ cảm biến và hiển thị lên LCD
            //Task_multiSensorScan();

            // Cập nhật thời gian của lần cập nhật cuối cùng
            lastUpdateTime = currentTime;
            Task_multiSensorScan();
            IdTimerCancle = TimerStart("delay", 500, 0, (void*)cancleTimer, NULL);
        }

        // Sleep để tránh lặp quá nhanh và gây tải CPU không cần thiết
        // Thời gian sleep có thể điều chỉnh tùy ý
        // Sleep 1 giây trước khi kiểm tra lại

}

int main(void){
	AppInitCommon();
	SetStateApp(STATE_APP_STARTUP);
	EventSchedulerAdd(EVENT_APP_INIT);
	lastUpdateTime =  GetMilSecTick();
	while(1)
	{
		processTimerScheduler();
		processEventScheduler();
		MultiSensorScan();
	}
}
